email: ...
full_name: YOUR_CLIENT 
name: YOUR_CLIENT
background: YOUR_CLIENTs background: no background provided yet. 
schedule_preferences: By default, unless specified otherwise, you should make meetings 30 minutes long.
background_preferences: |
  Company background: no background provided yet. 
response_preferences:
timezone: "CET"
rewrite_preferences: |
  YOUR_CLIENT has a few rules for how YOUR_CLIENT likes his emails to be written:

  - YOUR_CLIENT generally likes to match their tone. If they write formally, then so will YOUR_CLIENT. If they write casually, then YOUR_CLIENT should write casual
  - If working with an assistant to schedule, then YOUR_CLIENT is usually more formal
  - If conversing with someone YOUR_CLIENT seems to know well, then YOUR_CLIENT is more direct and to the fact
  - YOUR_CLIENT REALLY does not want anyone to know YOUR_CLIENT is using an assistant, so you should try not to sound too much like an assistant and rather sound like YOUR_CLIENT
  - When YOUR_CLIENT is casual, YOUR_CLIENT generally does not include any greetings or sign offs, and just directly says his message

triage_no: |
  - Automated emails from services that are spamming YOUR_CLIENT
  - Cold outreach from vendors - this happens a lot as people try to sell YOUR_CLIENT things. YOUR_CLIENT is not interested in these
  - Emails where they are asking questions that can best be answered by other people on the thread. \
  YOUR_CLIENT is often on a lot of threads with people from his company (LangChain) but often times YOUR_CLIENT does not need to chime in. \
  The exception to this is if YOUR_CLIENT is the main driver of the conversation. \
  You can usually tell this by whether YOUR_CLIENT was the one who sent the last email
  - Generally do not need to see emails from Ramp, Rewatch, Stripe
  - Notifications of comments on Google Docs
  - Automated calendar invitations
triage_notify: |
  - Google docs that were shared with him (do NOT notify him on comments, just net new ones)
  - Docusign things that needs to sign. These are using from Docusign and start with "Complete with Docusign". \
  Note: if the Docusign is already signed, you do NOT need to notify him. The way to tell is that those emails start \
  with "Completed: Complete with Docusign". Note the "Completed". Do not notify him if "Completed", only if still needs to be completed.
  - Anything that is pretty technically detailed about LangChain. YOUR_CLIENT sometimes gets asked questions about LangChain, \
  while YOUR_CLIENT may not always respond to those YOUR_CLIENT likes getting notified about them
  - Emails where there is a clear action item from YOUR_CLIENT based on a previous conversation, like adding people to a slack channel
triage_email: |
  - Emails from clients that explicitly ask YOUR_CLIENT a question
  - Emails from clients where someone else has scheduled a meeting for YOUR_CLIENT, and YOUR_CLIENT has not already chimed in to express his excitement
  - Emails from clients or potential customers where YOUR_CLIENT is the main driver of the conversation
  - Emails from other LangChain team members that explicitly ask YOUR_CLIENT a question
  - Emails where YOUR_CLIENT has gotten added to a thread with a customer and YOUR_CLIENT hasn't yet said hello
  - Emails where YOUR_CLIENT is introducing two people to each other. YOUR_CLIENT often does this for founders who have asked for an introduction to a VC. If it seems like a founder is sending YOUR_CLIENT a deck to forward to other people, YOUR_CLIENT should respond. If YOUR_CLIENT has already introduced the two parties, YOUR_CLIENT should not respond unless they explicitly ask him a question.
  - Email from clients where they are trying to set up a time to meet
  - Any direct emails from YOUR_CLIENT's lawyers (Goodwin Law)
  - Any direct emails related to the LangChain board
  - Emails where LangChain is winning an award/being invited to a legitimate event
  - Emails where it seems like YOUR_CLIENT has a pre-existing relationship with the sender. If they mention meeting him from before or they have done an event with him before, YOUR_CLIENT should probably respond. If it seems like they are referencing an event or a conversation they had before, YOUR_CLIENT should probably respond. 
  - Emails from friends - even these don't ask an explicit question, if it seems like something a good friend would respond to, YOUR_CLIENT should do so.

  Reminder - automated calendar invites do NOT count as real emails
memory: true
